# Generated by Django 5.0.2 on 2024-02-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Selling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_type', models.CharField(choices=[('Instant Selling', 'Instant Selling'), ('Advance Selling', 'Advance Selling')], max_length=50)),
                ('Bricks_type', models.CharField(choices=[('Number 1', 'Number 1'), ('Number 2', 'Number 2'), ('Number 3', 'Number 3'), ('picked', 'picked'), ('Half Bricks', 'Half Bricks')], max_length=50)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_mobile', models.IntegerField()),
                ('product_rate', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('payment', models.IntegerField()),
                ('commission', models.IntegerField(default=0)),
                ('due', models.IntegerField(default=0)),
            ],
        ),
    ]
