# Generated by Django 5.0.2 on 2024-02-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selling',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='selling',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
