# Generated by Django 5.0.2 on 2024-03-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0002_selling_is_delivered_selling_is_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='due',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='selling',
            name='payment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='selling',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
