# Generated by Django 5.0.2 on 2024-04-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0004_selling_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling',
            name='issue_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
