# Generated by Django 5.0.2 on 2024-05-16 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selling', '0005_alter_selling_issue_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selling_payment_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('issue_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
