# Generated by Django 5.0.2 on 2024-02-28 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selling_id', models.IntegerField()),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_address', models.CharField(max_length=200)),
                ('customer_mobile', models.IntegerField()),
                ('product_quantity', models.IntegerField()),
                ('pending_delivery', models.IntegerField(default=0)),
                ('delivered', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_amount', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.delivery')),
            ],
        ),
    ]
