# Generated by Django 5.0.2 on 2024-03-19 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='delivery_history',
            old_name='name',
            new_name='delivery',
        ),
    ]
