# Generated by Django 5.0.2 on 2024-04-14 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_rename_name_delivery_history_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_history',
            name='driver_name',
            field=models.TextField(blank=True, default='None', max_length=100),
        ),
    ]
