# Generated by Django 5.0.2 on 2024-04-19 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labour', '0002_remove_labourbill_labour_section_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production', models.IntegerField()),
                ('description', models.TextField(max_length=200)),
                ('total_bill', models.IntegerField()),
                ('paid_bill', models.IntegerField()),
                ('due_bill', models.IntegerField()),
                ('labour_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labour.labourdeal')),
            ],
        ),
    ]
