# Generated by Django 5.0.2 on 2024-03-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labourbill',
            name='labour_section',
        ),
        migrations.RemoveField(
            model_name='labourbill',
            name='sarder_name',
        ),
        migrations.AddField(
            model_name='labourdeal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='labourbill',
            name='payment_date',
            field=models.DateField(auto_now=True),
        ),
    ]
