# Generated by Django 5.0.2 on 2024-04-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0002_remove_labourbill_labour_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourdeal',
            name='payment_sequence',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('production', 'production'), ('Daily', 'Daily')], max_length=20),
        ),
    ]
