# Generated by Django 5.0.2 on 2024-04-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0004_rename_payment_date_labourbill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labourbill',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
