# Generated by Django 5.0.2 on 2024-05-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labour', '0005_alter_labourbill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourdeal',
            name='complete_production',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='labourdeal',
            name='season_target',
            field=models.IntegerField(default=0),
        ),
    ]
