# Generated by Django 5.0.2 on 2024-03-19 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Petroleum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petroleum_type', models.CharField(choices=[('Coal', 'Coal'), ('Wood', 'Wood')], max_length=10)),
                ('vendor_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('done_payment', models.IntegerField()),
                ('due', models.IntegerField()),
                ('issue_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('sarder_name', models.CharField(max_length=50)),
                ('done_payment', models.IntegerField()),
                ('due', models.IntegerField()),
                ('issue_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
