# Generated by Django 5.0.2 on 2024-04-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0002_alter_soil_done_payment_alter_soil_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petroleum',
            name='done_payment',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='due',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='petroleum',
            name='total_price',
            field=models.FloatField(),
        ),
    ]
