# Generated by Django 5.0.2 on 2024-04-18 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raw_materials', '0003_alter_petroleum_done_payment_alter_petroleum_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petroleum',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='soil',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
